### ISSUE TITLE
Is there a size limit for a favicon?

### ISSUE THREAD

**Issue by ua549** [muffinresearch/favicon-customizer#1]
Only the first custom favicon works. The others I set up (2 & 3 & 4) do not work.
They are supposed to be on the bookmark toolbar.
Some of the png files are 32 x 32 while the others are 64 x 64, 32 x 32 and 256 x 256.
Is there a preferred size? a size limit?  
If so, a mention in the addon information would help.

**Comment by muffinresearch** [comment]
@ua549 please can you provide examples that aren't working for you and I'll investigate.

**Comment by ua549** [comment]
Favicon Customizer has 3 icons defined.  Only the first one works.
Attached is a screen shot.
 
UA

**Comment by muffinresearch** [comment]
@ua549 I don't see a screenshot. Can you try attaching from the github UI? Better still if you can attach the problematic favicon to the image that would be even better.

**Comment by ua549** [comment]
![faviconcustomizer](https://user-images.githubusercontent.com/34217847/33554110-6dd11fac-d8c9-11e7-9c4f-d25c69f0307f.png)
![default](https://user-images.githubusercontent.com/34217847/33554155-9b83fd34-d8c9-11e7-8ac5-9e52ac6e3ef8.png)
![libsymbol](https://user-images.githubusercontent.com/34217847/33554323-3372488a-d8ca-11e7-91fc-823900d275d8.png)
![roadrunner](https://user-images.githubusercontent.com/34217847/33554352-4f320010-d8ca-11e7-9c36-fb1f454bb5cc.png)

**Comment by ua549** [comment]
Attached is a screenshot and three icons.  The $ icon is the only one that works.  All files are png format.

UA

**Comment by muffinresearch** [comment]
@ua549 so I've just tried the other two icons and they work fine for other site settings that work. So sizing isn't an issue. 

For the the second one - try removing the string "Library" from the page title string. I think that might be the issue. Bear in mind you might need to refresh the page after making a change.

**Comment by ua549** [comment]
No joy.  Only the $ works. I reversed the sequence putting roadrunner first and $ last. Still only the $ works.

BTW it would be nice if the first entry could be removed with a button like the others.

UA

**Comment by muffinresearch** [comment]
@ua549 please keep the issue open if there's still a problem.

It's working for me see:

![home_room_-__private_browsing__and_add-ons_manager_and_desktop](https://user-images.githubusercontent.com/1514/33557498-520ad520-d8ff-11e7-80a9-2926cf512912.jpg)

**Comment by muffinresearch** [comment]
Can you confirm what version of Firefox you're using and on what platform ?

**Comment by ua549** [comment]
I've tested it on Firefox 57.0.1 w/Windows 10 build 16299 and Nightly 59.0a1 w/Windows10 build 17046. 
The $ works on 59.0a1 but not on 57.0.1.

**Comment by ua549** [comment]
![favicon-changer](https://user-images.githubusercontent.com/34217847/33580285-8b4c2f3a-d91a-11e7-81cd-88058cc78019.png)

**Comment by muffinresearch** [comment]
Are you saying that the bookmark doesn't match or that the favicon is not replaced in the tab? 

The customizer only changes the favicon for the site and _won't change it in the bookmark_.

If you are still having an issue with the favicon replacement  then if you can provide full details I can look into it.

I'll need an example that doesn't work with the following: 

* Url of the site where the favicon is not replaced.
* Favicon customizer settings (either by screenshot or text)
* The favicon used as a replacement.

Please include as much detail as possible and please validate that you can reproduce the steps to reproduce the issue.

**Comment by ua549** [comment]
I figured it out.  The instance where the tab did not match the entry in favicon-customizer is because the url submitted is different than the responding url.
In 2 instances the bookmark favicon changed to match the entry in favicon-customizer. 
 
At this point changing the favicon in the bookmark is a feature request.
 
Thank you for your time and effort.
 
UA

**Comment by muffinresearch** [comment]
@ua549 glad you got it sorted!
