### ISSUE TITLE
Problems with Options Page + Dark Reader Addon

### ISSUE THREAD

**Issue by bellyrose** [muffinresearch/favicon-customizer#34]
I use a Firefox Extension called Dark Reader to automatically add a custom dark mode to websites that don't have them. The problem is that this also affects whatever website is used for the options page of this extension. Would you be willing to share the website where the options menu is hosted so I can add it to a filter to prevent Dark Reader from changing it?
![Favicon Customizer Options with Dark Reader](https://user-images.githubusercontent.com/34819855/71858125-11dc7e00-30b8-11ea-89db-4352d2410d1b.PNG)

**Comment by muffinresearch** [comment]
This should have been fixed in v0.6
